### ISSUE TITLE
lazyImageResource error on Compose for Desktop (JVM) with latest Compose builds

### ISSUE THREAD

**Issue by Jorkoh** [alialbaali/Kamel#4]
Trying to use lazyImageResource() with Compose Desktop builds `0.4.0-build190` and above will throw
`Exception in thread "AWT-EventQueue-0 @coroutine#3" java.lang.NoSuchMethodError: 'void androidx.compose.runtime.Composer.startReplaceableGroup(int, java.lang.String)'`

Seems to be related to the launch of [Compose 1.0.0-beta07](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.0.0-beta07) which comes with the following note:

> Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
> java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. ([Ia34e6](https://android-review.googlesource.com/c/platform/frameworks/support/+/1698012))

**Comment by alialbaali** [comment]
Please check with version `0.2.1` and let me know!

**Comment by Jorkoh** [comment]
Looks good, thanks!
